### ISSUE TITLE
Artículos sobre Angular en español

### ISSUE THREAD

**Issue by diegologs** [comunidad-tecnologica/comunidad-tecnologica#1]
Repositorio con recursos de interés: https://github.com/Frostqui/angular-espanol

**Comment by rachelcarmena** [comment]
¡¡ Gracias @Frostqui !! ¡¡ Está genial !! :tada: Ya eres miembro, ¡¡bienvenido!! :tada: Aún le estamos dando forma a esto, así que todo feedback también es bienvenido :wink:

**Comment by rachelcarmena** [comment]
Hola @Frostqui , la invitación aún está pendiente de aceptar :eyes: 
Reabro para que no se me olvide añadirte en el listado cuando la aceptes :wink: 
¡¡Gracias!!

**Comment by rachelcarmena** [comment]
Muchas gracias @Frostqui, ya hemos añadido una sección de recursos específicos :tada: [Comunidad Tecnológica](https://comunidad-tecnologica.github.io/)
