### ISSUE TITLE
This is a repository listing companies which offer full-time remote jobs with Spanish contracts

### ISSUE THREAD

**Issue by alexpdp7** [comunidad-tecnologica/comunidad-tecnologica#13]
Hola,

Estamos creando un listado de empresas que ofrecen trabajo remoto con contrato en España en:

https://github.com/remote-es/remotes

Creo que podría ser interesante incluirlo en vuestros listados de recursos.

Saludos,

Álex

**Comment by rachelcarmena** [comment]
¡¡¡ Muchas gracias @alexpdp7 !!! :tada: ¡¡¡ Añadido !!! :+1:
