### ISSUE TITLE
Newsletter PHP de JR a sr

### ISSUE THREAD

**Issue by mchojrin** [comunidad-tecnologica/comunidad-tecnologica#6]
Escribo un newsletter semanal con consejos para devs php que buscan pasar de JR. A sr. Lo pueden leer en https://us11.campaign-archive.com/?u=0bb6776b64fa1fcfc7a4d08c1&id=8f30adb5f4 y también hago un podcast para expertos it que están evaluando pasar a la docencia en anchor.fm/docentes-tech

**Comment by mericp** [comment]
Hola @mchojrin, puedes enviarnos una PR para añadir tu newsletter? Aquí puedes ver el formato: https://github.com/comunidad-tecnologica/newsletters/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R10
Gracias!

**Comment by mchojrin** [comment]
@mericp Claro! Gracias!!
