### ISSUE TITLE
[Solicitud miembro] Zaragoza

### ISSUE THREAD

**Issue by Miguel000** [comunidad-tecnologica/comunidad-tecnologica#7]
Hola!

Me llamo Miguel, soy de Zaragoza y me parece una iniciativa increible y creo que podría aportar mi granito de arena. Suelo participar más en conferencias de seguridad pero suelo estar al tanto de todo lo que aparece y me gustaría participar en repo de Zaragoza que me parece que estáis buscando. 

Un saludo.

**Comment by rachelcarmena** [comment]
Hola @Miguel000 !! Claro, te invito. ¡¡Muchas gracias!! :tada:

**Comment by rachelcarmena** [comment]
Por favor, reabre en caso de que no te llegue la invitación :wink:
